const fish = [
  {
    id: 1,
    name: "Prawns",
    price: "50",
    like: true,
    img: require("../assets/raw2.jpg"),
    about:
      "Succulent fresh fish from source  fresh fish from source  fresh fish from source"
  },
  {
    id: 2,
    name: "Red Fish",
    price: "100",
    like: false,
    img: require("../assets/cassava.jpg"),
    about: "Succulent fresh fish from source",
  },
  {
    id: 3,
    name: "Cat Fish",
    price: "50",
    like: true,
    img: require("../assets/cassava.jpg"),
    about: "Succulent fresh fish from source",
  },
  {
    id: 4,
    name: "Oceanp-Mix",
    mix:"SHRIMP, SQUID,CLAMS,OCTOPUS",
    price: "55",
    like: true,
    img: require("../assets/cassava.jpg"),
    about:
      "Succulent fresh fish from source fresh fish from source",
  },
  {
    id: 5,
    name: "Cat Fish",
    price: "60",
    like: true,
    img: require("../assets/cassava.jpg"),
    about: "Succulent fresh fish from source",
  },
  {
    id: 6,
    name: "Cat Fish",
    price: "65",
    like: true,
    img: require("../assets/cassava.jpg"),
    about: "Succulent fresh fish from source",
  },
  {
    id: 7,
    name: "Cat Fish",
    price: "50",
    like: true,
    img: require("../assets/cassava.jpg"),
    about: "Succulent fresh fish from source",
  },
  {
    id: 8,
    name: "Cat Fish",
    price: "50",
    like: true,
    img: require("../assets/cassava.jpg"),
    about: "Succulent fresh fish from source",
  },
  {
    id: 9,
    name: "Cat Fish",
    price: "50",
    like: true,
    img: require("../assets/cassava.jpg"),
    about: "Succulent fresh fish from source",
  },
  {
    id: 10,
    name: "Cat Fish",
    price: "50",
    like: true,
    img: require("../assets/cassava.jpg"),
    about: "Succulent fresh fish from source",
  },
];
export default fish;
